### ISSUE TITLE
Add spoilers cog.

### ISSUE THREAD

**Issue by Injabie3** [SFUAnime/Ren#105]
# Feature request

#### Select the type of feature you are requesting:
- [x] Cog
- [ ] Command
- [ ] API functionality

#### Describe your requested feature
Have a cog that emulates a spoiler tag in many forums we've seen before.  Probably can follow a format as follows:
- Check all messages for `[spoiler]` prefix, and assume the following steps is when it detects one.
- Store the message contents, and delete the message.
- In the channel that triggered this, send a message with something along the lines of `SPOILER, react to see the message`, and get the message ID
- Store the message ID in a "database", along with the message.
- If anyone reacts to the message, send the message contents to them via DM.

We will need two listeners, one for checking all messages, and one for checking reacts.

Things to think about:
- [x] Word filter integration: make sure we store the filtered message? or do we filter on the fly?
- [x] Should we delete reactions after they are used?  Maybe a good idea.
- [x] Make sure to handle case where a user has denied DMs from the bot.
- [ ] Configurable settings?  Prefix for the spoiler?  On/off toggle (as opposed to unloading cog).

**Comment by KamiCreed** [comment]
Should completely delete the message if the spoiler contains a filtered word and DM the message (filtered?) to the user. Probably inside the word filter cog, check if `[p]spoiler` exists as the first word or something. Also, check if the `spoiler` cog is loaded.

**Comment by Injabie3** [comment]
Done as per #108, #110, #111, and #112
