### ISSUE TITLE
Fast Message Deletion still appears on Mobile

### ISSUE THREAD

**Issue by KamiCreed** [SFUAnime/Ren#114]
# Command bugs

#### Command name

`renspoiler` and also `renword_filter`

#### What cog is this command from?

spoiler and word_filter

#### What were you expecting to happen?

Deletions by the bot should be reflected on discord mobile apps.

#### What actually happened?

The message deleted still exists on the mobile clients, probably due to how fast the bot deleted the message and the client did not have time to register the delete.

#### How can we reproduce this issue?

`renspoiler <msg>` on the PC while looking at the same channel on the mobile app. Probably similar for word_filter (Say a filtered word).

**Comment by KamiCreed** [comment]
I remember we talked about attempting to multi-delete the message or as a last resort to introduce a delay before deleting.

**Comment by Injabie3** [comment]
Yes, let's try that and see if it throws an exception.

**Comment by Injabie3** [comment]
Yeah it might not be feasible: here's a loop trying to delete it twice:
```py
531         for _ in range(0, 2):
532             await self.bot.delete_message(msg)
```
and it throws an exception even with 2.
```sh
Ignoring exception in message
Traceback (most recent call last):
  File "lib/discord/ext/commands/bot.py", line 252, in _run_extra
    yield from coro(*args, **kwargs)
  File "/home/ryan/github/Rin/cogs/word_filter.py", line 532, in checkWords
    await self.bot.delete_message(msg)
  File "lib/discord/client.py", line 1263, in delete_message
    yield from self.http.delete_message(channel.id, message.id, guild_id)
  File "lib/discord/http.py", line 198, in request
    raise NotFound(r, data)
discord.errors.NotFound: NOT FOUND (status code: 404): Unknown Message
```

**Comment by KamiCreed** [comment]
Yea. I suppose it makes sense. It's probably just the mobile client being slow to respond... Not sure if there's a good fix to that besides a delay...

**Comment by Injabie3** [comment]
Hmm, and even with a delay, there's still a possibility that the mobile client might not get the update for it, especially if the connection is flaky.  💭 💭

**Comment by Injabie3** [comment]
Closing as `wontfix`
