### ISSUE TITLE
[Misc] Upgrade to Red-DiscordBot v3

### ISSUE THREAD

**Issue by Injabie3** [SFUAnime/Ren#117]
We should explore the option of upgrading the bot from **Red-DiscordBot v2** to **Red-DiscordBot v3**, as the discord.py API we're using right now is getting old (over a year now).  It won't be smooth, since there are breaking API changes, and custom cogs will need to be updated.

This will definitely be an "after-exam" project to look at, would be good to have some others to help in this regard.

Things to do:
- [ ] Data migration: Check if we can use the v2 -> v3 data migration tool.
- [ ] Tags: check upstream to see if it's been upgraded.
- [ ] Custom cogs: Make sure we're using the Config API as outlined in Red-DiscordBot.

**Comment by Tetimaru** [comment]
Just leaving this here so I remember: Standardize the check file/folder system functions in a separate module and not define the function for every cog.

**Comment by Injabie3** [comment]
Closing for now, wait for 3.0.0 release for the meantime and maintain cogs.

**Comment by Injabie3** [comment]
Stable release upstream means we can take a look and try it out 🎉

**Comment by Injabie3** [comment]
Closing since the important cogs are done.
