### ISSUE TITLE
[Spoilers] Check for react permissions

### ISSUE THREAD

**Issue by Injabie3** [SFUAnime/Ren#122]
#### Command name
`renspoiler <msg>`

#### What cog is this command from?
`spoilers.py`

#### What were you expecting to happen?
Spoiler to be generated, but then again, the bot can't react, so we should abort.

#### What actually happened?
Spoiler is generated and saved, reaction cannot be made, and exception is thrown in console and as a Discord message.

#### How can we reproduce this issue?
`renspoiler <msg>` in any channel with no react permissions for the bot.

**Comment by Tetimaru** [comment]
Cannot reproduce this issue.

**Comment by Injabie3** [comment]
Let me give you permissions to modify channel permissions.

**Comment by Injabie3** [comment]
Okay, try again.
