### ISSUE TITLE
[Highlight] DM gets sent even if triggering message is deleted

### ISSUE THREAD

**Issue by Injabie3** [SFUAnime/Ren#123]
# Other bugs

#### What were you trying to do?
n/a.  Message containing triggered word was filtered, and is deleted by WordFilter cog.

#### What were you expecting to happen?
No notification.

#### What actually happened?
Notification via DM is sent, with the context not containing the triggered word.

#### How can we reproduce this issue?
Get someone to trigger your highlight word with a filtered word.

**Comment by Tetimaru** [comment]
Could you elaborate on reproduction steps? Can you not reproduce this with your own messages? What do you mean by "highlight word"?

**Comment by Injabie3** [comment]
So for this one, if you do `[p]highlight add <word>`, then when someone types `<word>` when you are idle (I think it was ~20 seconds without sending a message), it'll DM you with the message contents, and some of the surrounding messages to give you some context on what the message is.
