### ISSUE TITLE
[Stars] Renstar random keeps trying to retrieve deleted highlights

### ISSUE THREAD

**Issue by KamiCreed** [SFUAnime/Ren#144]
# Command bugs

#### Command name

```
renstar random
```

#### What cog is this command from?

Stars cog

#### What were you expecting to happen?

Retrieval of stars/highlights that have not been deleted more smoothly.

#### What actually happened?

Ren constantly tries to get a deleted highlight. These ones should probably be removed from the internal database if possible.
![image](https://user-images.githubusercontent.com/9517086/49131678-ed478d00-f28d-11e8-986b-8bcf33de7d91.png)

#### How can we reproduce this issue?

```
renstar random
```
When there have been deleted highlights probably.

**Comment by KamiCreed** [comment]
This is probably a side effect from auto deleting one starred highlights. Either we very infrequently check all of the current highlights and remove them from the JSON or whatever is used, or somehow remove them when they are deleted.

**Comment by Injabie3** [comment]
That seems to be what it looks like, since I see a bunch of orphaned messages with 2 or less users.

**Comment by Injabie3** [comment]
Okay, so a few things to do here:
1. Modify the prune method to also remove the corresponding message ID from the db.
2. Add a method to check all messages within the db to see if they exist.  If they do not, prune it from the database.

**Comment by Injabie3** [comment]
Closing as we're no longer using v2 starboard.
