### ISSUE TITLE
[Stars] Link image preview embed in highlights

### ISSUE THREAD

**Issue by KamiCreed** [SFUAnime/Ren#145]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature

I noticed that image link embedding was done for `renspoiler` and I feel that can also be done for `renstar` highlights. Basically, for example, when a twitter link is highlighted, if possible, it'll show the text, but if not, it would be nice to at least show the image of the link in the rich text highlights.

**Comment by Injabie3** [comment]
@Tetimaru

**Comment by Injabie3** [comment]
Closing, since V3 has this capability from third party cog.
