### ISSUE TITLE
[Tags] Check for existing command

### ISSUE THREAD

**Issue by Injabie3** [SFUAnime/Ren#189]
Since `tags` has been coupled with `aliases`, it is possible to add tags that have the same name as commands.  We need to add the checking logic from aliases to tag creation to make sure we can check this properly.

**Comment by KaguneAstra** [comment]
This issue has been fixed in https://github.com/SFUAnime/Ren/commit/10fa5d274d98acd856d5d35c3b222155185a309d

Closing this issue now
