### ISSUE TITLE
[Highlight] Increase inactivity timer on renhighlight

### ISSUE THREAD

**Issue by AndyRLP1996** [SFUAnime/Ren#205]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature

Please increase the inactivity timer check on highlight from 20 seconds, perhaps to 30 or 45 seconds.

**Comment by Injabie3** [comment]
Merged in at f8dd80ed6ad2b18963621e4bb418e5efdb0a16cf
