### ISSUE TITLE
[Respects] Give helpful message when bot doesn't have Manage Message permissions

### ISSUE THREAD

**Issue by Injabie3** [SFUAnime/Ren#213]
When a bot cannot send a message, problem is apparent: no send permissions, but no error message shows up on the channel because of it.

When a bot cannot delete messages, problem is shown to users.  Make the message more graceful to inform users of the actual error: missing Manage Message permissions.

**Comment by KamiCreed** [comment]
🤔 "good first issue"

**Comment by Injabie3** [comment]
The PR above actually solves #163, reopening.

**Comment by KaguneAstra** [comment]
solved as of e4258a5
