### ISSUE TITLE
[Highlight] Add a message content based blacklist to renhighlight.

### ISSUE THREAD

**Issue by AndyRLP1996** [SFUAnime/Ren#215]
# Feature request

#### Select the type of feature you are requesting:

- [ ] Cog
- [x] Command
- [ ] API functionality

#### Describe your requested feature

Add a blacklist for message content. Have highlight not trigger if a tag from the content blacklist is in the message.

Example usage where X is on the highlight blacklist and Y is on the blacklist.

"X" - triggers
"X Y" - doesn't trigger
"X *some text* Y" - doesn't trigger

**Comment by Injabie3** [comment]
We're in the process of upgrading this to use the new discord.py API, hoping to do this soon after that migration is done 🙏

**Comment by Injabie3** [comment]
WIP

**Comment by Injabie3** [comment]
Merged in as of 49135b2f50521a97f7d47ac7cf9f3f3c93dff482
