### ISSUE TITLE
[Misc] Mass download avatar images

### ISSUE THREAD

**Issue by Injabie3** [SFUAnime/Ren#230]
For archival purposes, make a command to download all avatars of users on the server.

Some requirements:
- Standard avatar size (e.g. 400px by 400px).
- Standard image format (e.g. jpeg).

To do:
- [x] Download avatars, save as `<id>.<img format>`.
- [ ] Perform post-processing of the images to standardize format.
- [ ] Add progress indicator so that we know the current image we're downloading (e.g. 100/700).
- [ ] Look into uploading this to a shared drive folder or something via some Google Drive API (?).  Would probably implement this as a separate command.

**Comment by Injabie3** [comment]
This should use the v1.x.x discord.py API, so bot v3.

**Comment by Injabie3** [comment]
How is this going so far?

**Comment by KaguneAstra** [comment]
I closed the file without saving and lost all of my progress

**Comment by Injabie3** [comment]
Partially complete as of commit f539e306aa2ef8636986037c3c9fd4f6458a7543

**Comment by Injabie3** [comment]
No further progress will be made for now, closing.
