### ISSUE TITLE
[TempChannels] Change deletion to remove visibility and later deletion.

### ISSUE THREAD

**Issue by KaguneAstra** [SFUAnime/Ren#277]
Rework duration to set the total duration the channel remains visible to the allowed roles

Create new sub-command that sets how long to wait to delete the channel after the channel is hidden.

Have bot remove role access after the duration is up and delete after the delete delay is finished.

**Comment by Injabie3** [comment]
As per our offline discussion:
- Add a flag to indicate archive and remove permissions from all.
- Add suffix to channel (may have to rename it to ensure name is not too long).
