### ISSUE TITLE
[Tags] Convert ALLOWED_ROLE into a variable

### ISSUE THREAD

**Issue by IAmTheRedSpy** [SFUAnime/Ren#297]
# Feature request

#### Select the type of feature you are requesting:

- [X] Cog
- [ ] Command
- [ ] API functionality

#### Describe your requested feature

The tags cog currently uses a constant to specify which roles can use the commands. This is inflexible and doesn't allow for portability to other servers. It should be changed to a variable that can be changed with a command.

https://github.com/SFUAnime/Ren/blob/91d26abbe92a0f426bd517b84f2e597f266d4a31/cogs/tags/constants.py#L6

**Comment by Injabie3** [comment]
Agreed, this was done to expedite merge.
