### ISSUE TITLE
[Tags] Remove duplicate function call in rolecheck

### ISSUE THREAD

**Issue by IAmTheRedSpy** [SFUAnime/Ren#298]
lower() is called on all role names on this line, even though they're already lowercase from previous lower() calls.

https://github.com/SFUAnime/Ren/blob/91d26abbe92a0f426bd517b84f2e597f266d4a31/cogs/tags/rolecheck.py#L39

**Comment by Injabie3** [comment]
Re-checked this logic, this is actually correct and not duplicated. It is a lambda function passed into the called function to check if a role in the invoking author matches one in the list. The `.name.lower()` in the lambda is applied to the author's roles and not the ones on the list.
