### ISSUE TITLE
[Respects] Improve readability

### ISSUE THREAD

**Issue by IAmTheRedSpy** [SFUAnime/Ren#300]
# Feature request

#### Select the type of feature you are requesting:

- [X] Cog
- [ ] Command
- [ ] API functionality

#### Describe your requested feature

cogs/respects/respects.py uses different language for when the config is [directly modified](https://github.com/SFUAnime/Ren/blob/91d26abbe92a0f426bd517b84f2e597f266d4a31/cogs/respects/respects.py#L106) or [read](https://github.com/SFUAnime/Ren/blob/91d26abbe92a0f426bd517b84f2e597f266d4a31/cogs/respects/respects.py#L127) compared to when [the whole config is loaded and then read](https://github.com/SFUAnime/Ren/blob/91d26abbe92a0f426bd517b84f2e597f266d4a31/cogs/respects/respects.py#L187). This makes it difficult to read and understand.

**Comment by quachtridat** [comment]
Closed via 52248f02748cc6dabb1d47d8441ad641b96267ee in #413.

Config values are now accessed by keys set by constants, and all related hardcoded parts have been refactored. Refer to #404 for more context.
