### ISSUE TITLE
[Filter] Replacing offending string

### ISSUE THREAD

**Issue by Injabie3** [SFUAnime/Ren#31]
Offending string can be replaced with a lot of stars if the regex string is long.
![regex](https://user-images.githubusercontent.com/6710854/29553019-79f59e2c-86ce-11e7-93f3-6337cce0ec8e.png)

**Comment by abuneri** [comment]
what was a test case input you had and the filter word/phrase that u used to do get this?

**Comment by Injabie3** [comment]
input:
``dd f,@.p.i.n.g``
regex:
``f[,|/|.| |||']*[o|0|a|A|4|@|#]+[,|/|.| |||']*p[,|/|.| |||']*[i|1|!][,|/|.| |||']*n[,|/|.| |||']*g``

I implemented a fix, haven't pushed it up yet though.

**Comment by Injabie3** [comment]
Actually, this was the one I used to test and implement fix:
input: 
```
f,@.p.i.n.g dd
```
regex: 
```
f[,|/|.| |||']*[o|0|a|A|4|@|#]+[,|/|.| |||']*p[,|/|.| |||']*[i|1|!][,|/|.| |||']*n[,|/|.| |||']*g
```
output:
```
**********************************************.i.n.g d
```

**Comment by abuneri** [comment]
sweet, thx!
