### ISSUE TITLE
[Birthday] Improving module 

### ISSUE THREAD

**Issue by abelathomas** [SFUAnime/Ren#323]
# Feature request
#### Select the type of feature you are requesting:
- [x] Cog 
- [ ] Command
- [ ] API functionality

#### Describe your requested feature
Proposing changes to the current birthday module for improving code quality ~~and sanity of people maintaining it~~.

### **Proposed commands:** 
**setrole** - Takes a role as input. Assigns the role to users on their birthday.
**list** - No input. Returns a Lists of birthdays of users.

**add** - Takes a user as input. Assigns them the birthday role.
**set** - Takes a user as input along with a day and month. Enters the given day and month as the user's birthday into the assigns &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;config, them the birthday role if today is their birthday.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*(day and month are optional parameters, if it is not provided, it will default to the current day and month)*

**del** - Takes a user as input. Removes the birthday role from the user.
**unset** - Takes a user as input. Remove the user's birthday role and birthday from the config.

Reducing variables needed to be stored: 
&nbsp;&nbsp;&nbsp;&nbsp;bool for a one day assigned role, 
&nbsp;&nbsp;&nbsp;&nbsp;day
&nbsp;&nbsp;&nbsp;&nbsp;month

The daily add and sweep, for assigning and unassigning users when the day changes can be left in its current implementation, only changing their variable and function calls to match with the ones used above.

**Comment by Injabie3** [comment]
Thanks for the issue, agreed would be good to refactor it. Proposal LGTM. Some things we could also do:
1. Thoughts on changing `setrole` to `role`? I think it's implied that we're setting the role anyways, no need to add redundant set.

For removing the other two day/month set variables, just double check to make sure the sweeper is only called once a day, else we'll need to still keep the day variable in.

**Comment by abelathomas** [comment]
Yeah sure, sounds good. 👍
