### ISSUE TITLE
[Misc] Remove paginator dependency

### ISSUE THREAD

**Issue by Injabie3** [SFUAnime/Ren#337]
There is a dependency in birthday, wordfilter, and tags (among others, probably) that requires the use of paginator, which was imported from the v2 days of the bot. We should transition to `discord.ext.menus` instead.

- [x] #435
- [x] #436
- [x] #437
- [x] #440
- [x] #456
- [x] #461

**Comment by Injabie3** [comment]
Another thing we could do is package `paginator` into a library cog, which would not add commands, but would be something you could fetch from another cog and use. This way it wouldn't require installing paginator in the cog and allows for other users of the cog to simply install the library cog first and then install birthday, wordfilter, etc.

**Comment by Injabie3** [comment]
Reference the [core audio cog, namely playlists](https://github.com/SFUAnime/Ren/blob/V3/testing/redbot/cogs/audio/core/commands/playlists.py), namely the `AsyncIter`, `menu`, and `pagify` imports.

**Comment by quachtridat** [comment]
_Continuation of #399._

The current version of `RoboDanny`'s `paginator` is essentially built upon `discord.ext.menus`, with additional level of code abstraction that gives a fairly nice paginating interface (`menus.SimplePages`) that does not require many changes to the existing codebase (as opposed to writing custom `PageSource`s for our use).

We could make `paginator` a separate cog and let it be a dependency for other cogs to use, as you suggested. I believe Python's conditional `import` could have it done. This way, I imagine `wordfilter` would refuse to be loaded if `paginator` is not present/working.

Feel like this is close to your plan, but maybe you would want to give some thoughts on this.

Nice to see behind the scenes of _Ren_ 👀

**Comment by Injabie3** [comment]
Good point with the conditional import. Will have to think about the approach some more I guess.

**Comment by Injabie3** [comment]
Missed one: `smartreact`
