### ISSUE TITLE
[Tags] Fix raw command

### ISSUE THREAD

**Issue by Injabie3** [SFUAnime/Ren#383]
Suppose we add the following tag:
```
`GitHub    :` <https://u.sfuani.me/git>
`Ren       :` <https://u.sfuani.me/ren>
Contributions are very welcomed, please feel free to start a discussion in <#223595096661164033>.
```
If we use the raw command to get it back, we get the following instead:
```
`GitHub    :` <https://u.sfuani.me/git%3E
`Ren       :` <https://u.sfuani.me/ren%3E
Contributions are very welcomed, please feel free to start a discussion in <#223595096661164033>.
```

**Comment by abelathomas** [comment]
Adding on this issue, links are changed as seen below
for example the following link: 
`https://www.youtube.com/playlist?list=PLpHQKBFP1_Sn4R2ajRHNRvKHXvrgCt5gu`

Once put into cc and outputted as a raw becomes the following,
`https://www.youtube.com/playlist?list=PLpHQKBFP1/_Sn4R2ajRHNRvKHXvrgCt5gu%3E`

`/` gets added ahead of the `_` which disrupts the original link.
