### ISSUE TITLE
[Low Priority] SmartReact Missing Permissions

### ISSUE THREAD

**Issue by KamiCreed** [SFUAnime/Ren#39]
### Type:

- [ ] Suggestion
- [X] Bug - Low priority

I wonder why we're getting this error:
```bash
SmartReact Error:
FORBIDDEN (status code: 403): Missing Permissions
```

Does Ren not have enough permissions to do the SmartReact or is something in the code going wrong? Doesn't seem like a huge deal, so this can be in low priority.

**Comment by Injabie3** [comment]
Ah yes, I suppressed the 403 errors, since this still gets triggered in #dark-hour

**Comment by Injabie3** [comment]
References commit https://github.com/ARG-TLQ/Red-DiscordBot/commit/446a851f054cd4befee46171ee6425e309da28c8
