### ISSUE TITLE
[Cogs] Refactor and remove hardcoded config calls

### ISSUE THREAD

**Issue by quachtridat** [SFUAnime/Ren#404]
### What component of Red (cog, command, API) would you like to see improvements on?

All applicable cogs.

### Describe the enhancement you're suggesting.

[`Red`](https://docs.discord.red/en/stable/framework_bot.html#redbot.core.bot.Red) supports several ways of getting/setting [`Config`](https://docs.discord.red/en/stable/framework_config.html#redbot.core.config.Config) [`Value`](https://docs.discord.red/en/stable/framework_config.html#redbot.core.config.Value)s and [`Group`](https://docs.discord.red/en/stable/framework_config.html#redbot.core.config.Group)s. Currently there are a number of cogs that use hardcode to access [`Config`](https://docs.discord.red/en/stable/framework_config.html#redbot.core.config.Config) fields, and we can use [`Config.get_attr(item: int | str)`](https://docs.discord.red/en/stable/framework_config.html#redbot.core.config.Group.get_attr) to get rid of hardcode and make use of constants instead.

For example, [cogs/respects/respects.py:124-125](https://github.com/SFUAnime/Ren/blob/51409fbc9f00a20fce4b4b393f754eaac09578cc/cogs/respects/respects.py#L124-L125)
```py3
        timeBetween = await self.config.guild(guild).timeSinceLastRespect()
        msgsBetween = await self.config.guild(guild).msgsSinceLastRespect()
```
can be rewritten as
```py3
        timeBetween = await self.config.guild(guild).get_attr(KEY_TIME_BETWEEN)()
        msgsBetween = await self.config.guild(guild).get_attr(KEY_MSGS_BETWEEN)()
```
making use of [cogs/respects/respects.py:16-17](https://github.com/SFUAnime/Ren/blob/51409fbc9f00a20fce4b4b393f754eaac09578cc/cogs/respects/respects.py#L16-L17)
```py3
KEY_TIME_BETWEEN = "timeSinceLastRespect"
KEY_MSGS_BETWEEN = "msgsSinceLastRespect"
```
or as
```py3
        timeBetween = self.config.guild(guild).get_attr(KEY_TIME_BETWEEN)
        msgsBetween = self.config.guild(guild).get_attr(KEY_MSGS_BETWEEN)
```
and do `await` `get`/`set` operations on them later on if necessary. For example, [cogs/respects/respects.py:131](https://github.com/SFUAnime/Ren/blob/51409fbc9f00a20fce4b4b393f754eaac09578cc/cogs/respects/respects.py#L131) can be rewritten as
```py3
        await ctx.send(msg.format(await msgsBetween(), await timeBetween()))
```
Similarly, [cogs/welcome/welcome.py:85](https://github.com/SFUAnime/Ren/blob/4b57b6da90b6f8cc823f89b36fd2a4af11ce631f/cogs/welcome/welcome.py#L85)
```py3
            await self.config.guild(guild).welcomeChannelSet.set(False)
```
can be rewritten as
```py3
            await self.config.guild(guild).get_attr(KEY_WELCOME_CHANNEL_ENABLED).set(False)
```

**Extra attention needed** when refactoring code within an asynchronous context manager code block. Refer to [`Red`](https://docs.discord.red/en/stable/framework_bot.html#redbot.core.bot.Red)'s [documentation](https://docs.discord.red/en/stable/framework_config.html) for extra reference and [best practices](https://docs.discord.red/en/stable/framework_config.html#best-practices-and-performance-notes).

Applicable cogs may include:
- [x] #406
- [x] #414
- [x] #409
- [x] #420
- [x] #419
- [x] #427
- [x] #405
- [x] #416
- [x] #449
- [x] #407
- [x] #422
- [x] #421
- [x] #438
- [x] #410

### Anything else?

This may as well resolve #300 by refactoring `all()` calls.
- [x] #300

**Comment by Injabie3** [comment]
We can skip third party cogs on this list, e.g. Starboard, Invoice, Heist, and Casino. They're checked in but not primarily maintained by us. We merge changes from them periodically from their respective parent projects, so not worth it to make changes to those here IMHO.

**Comment by Injabie3** [comment]
Closing because this effort is now complete.
