### ISSUE TITLE
[AfterHours] Auto-purge inactive users

### ISSUE THREAD

**Issue by Injabie3** [SFUAnime/Ren#452]
If a user hasn't talked in the channel for a certain amount of time X (measured in hours), auto remove the after-hours role from them. X should be configurable from a `[p]afterhours` subcommand.

**Comment by quachtridat** [comment]
Might give this a go.

Purging based on past messages:
1. Obtain `after-hours` role.
2. Obtain role members.
3. Obtain `after-hours` channel.
4. Obtain the channel's history.
5. Filter out all role members whose messages are in the channel within `X` hours.
6. Purge the rest of the role members.

The above does not work when the channel is not present, so I am not sure if there is a better approach. Also not sure when/how often the auto-purge happens and whether it is configurable.

Another way is saving a timestamp for every role member's most recent `after-hours` message, and purging based on that.

The command could be `[p]afterhours autopurge inactivehours X`. `X` is an integer, rendered invalid for any negative numbers, takes effect for any positive numbers, and disables the mechanism itself when `X = 0`.

**Comment by Injabie3** [comment]
Yep, timestamp approach was the one I was thinking of. You'll have the after-hours channel IDs already because we react to the channel creation, so we can listen for messages and update if the channel IDs match those on that list.
