### ISSUE TITLE
[Triggered] Clean up GIFs after sending

### ISSUE THREAD

**Issue by Injabie3** [SFUAnime/Ren#453]
After creating the animated triggered file, we never clean it up. We should delete the file once we're done with it to avoid taking up unnecessary disk space.

**Comment by quachtridat** [comment]
As discussed sideband, an alternative that would help is to not store images as files, but rather work with their data (byte-streams) to make triggered images and then let `Discord.py` handle them.

Reference: [`cogs/sfu/roads.py:124`](https://github.com/SFUAnime/Ren/blob/V3/testing/cogs/sfu/roads.py#L124)
