### ISSUE TITLE
[Timeout] Add ability to self-timeout

### ISSUE THREAD

**Issue by Injabie3** [SFUAnime/Ren#534]
This is dependent on timeout support in dpy, which if I recall correctly, doesn't exist in the version of dpy we're using right now (should double check this).

As per title, we're seeing people requesting for timeouts (the question of "why" shall be deferred from this discussion). We should see if we can add a command that lets people specify a duration to be timed out for.

**Comment by quachtridat** [comment]
According to the announcement from ~~his excellency~~ [Rapptz/Danny](https://gist.github.com/Rapptz) @ https://gist.github.com/Rapptz/c4324f17a80c94776832430007ad40e6, timeouts are being implemented, so yes, it doesn't exist in the version of `discord.py` we are using right now.

On the topic of self-timeout, would it be a piece of simple information that sticks to a member (e.g.,`[p]selftimeout info <user>` shows date/time/duration the `<user>` would want to be timed-out), or would it also be a reminder that notify specific people or channels (those who have the permissions to execute timeout)? I could imagine a cog that aggregates "timeout requests" coming from different members and it will then be up to those authorized to timeout them accordingly.

**Comment by Injabie3** [comment]
Closing for now, no real need for this.
