### ISSUE TITLE
[Cogs] Convert for dpy2 support

### ISSUE THREAD

**Issue by Injabie3** [SFUAnime/Ren#535]
Although discord.py v2 support is not ready yet, we should look at verifying cog support soon. List of cogs in order of importance:
- [x] #539
- [x] #536
- [x] #540
- [x] #541
- [x] #545
- [x] #546
- [x] #542
- [x] #547
- [x] #538
- [x] #548
- [x] #549
- [x] #550
- [x] #551
- [x] [GoodSmileInfo] Convert for dpy2 support
- [x] #576
- [x] #552
- [x] #592

**Comment by quachtridat** [comment]
Finished.
