### ISSUE TITLE
[Economy] Do not allow wiping a file if you cannot read the file.

### ISSUE THREAD

**Issue by Injabie3** [SFUAnime/Ren#55]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [x] Suggestion
- [x] Bug

### Brief description of the problem
If there is a syntactical error in the json file to load, the cog will replace it with an empty file.  Sigh...

### Expected behavior
Cog will not load.
### Actual behavior
Cog loads, wipes json file.
### Steps to reproduce

1. Unload cog.
2. Edit the bank.json file, and make a syntactical error.
3. Save the change, and leave.
4. Reload the cog.
5. Load bank.json.  It will be empty.

**Comment by TwelveNights** [comment]
Resolves issue #55
