### ISSUE TITLE
[Timezone?] Bot running ahead by 7 hours

### ISSUE THREAD

**Issue by abelathomas** [SFUAnime/Ren#553]
For some reason, the bot seems to be running ahead by 7 hours. 
Not sure of the cause of it, but the bug can be seen when a new poll is started, the poll will only end 7 hrs after the predetermined end time. https://discord.com/channels/222841664585072641/761123970975793192/970029009939353660
This behaviour can also be seen in the defender cog, when a new account joins, 
![image](https://user-images.githubusercontent.com/14364577/166177878-97dcd910-3b31-42bf-9586-d96a549f5f36.png)

**Comment by Injabie3** [comment]
Screenshot was from the defender cog, this should be resolved by https://github.com/Twentysix26/x26-Cogs/pull/49 .
