### ISSUE TITLE
[Tags] Associate aliased tags with original alias.

### ISSUE THREAD

**Issue by Injabie3** [SFUAnime/Ren#56]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [x] Suggestion
- [ ] Bug

### Brief description of the problem
See below.
<img width="705" alt="screen shot 2018-05-16 at 21 14 57" src="https://user-images.githubusercontent.com/6710854/40264875-2c69e10c-5ae2-11e8-9bb3-c1ca01b4a54b.png">

**Comment by Injabie3** [comment]
Updated screenshot cause clearly I can't upload the correct file

**Comment by TwelveNights** [comment]
Could you elaborate more on this issue? I don't understand what the problem is exactly

**Comment by Injabie3** [comment]
Have to re-ping them for more info, I don't remember since it's been a while.  If I recall correctly, it was something along the lines of having more than one alias linking to one particular tag.

**Comment by Injabie3** [comment]
Closing as `wontfix`.
