### ISSUE TITLE
[Tags] Better handle raw content exceeding max message length

### ISSUE THREAD

**Issue by quachtridat** [SFUAnime/Ren#568]
## Summary

`[p]tag raw <tag name>` (as of https://github.com/SFUAnime/Ren/commit/646d6c9366ae8e1fded698cd2204b184f94d3183) fails when the raw content exceeds Discord's maximum message length. Note that the tag does exist because it does not exceed Discord's maximum message length, but the raw content of it (i.e., with markdown text formatters escaped) does.

## Reproduction

1. Create a tag where message length is as close to the message length limit as possible, and has many text formatters.
2. Get the raw content of that tag via `[p]tag raw <tag name>`.

## Potential solutions

Solutions are still being discussed, however two potential solutions are being considered:

1. The cog sends two split messages with no text wrapping (i.e., the first message's length is always at limit), or
2. The cog sends a text file containing the full raw content of the tag.

Open to ideas and feedback.

**Comment by Injabie3** [comment]
Not a fan of sending a text file. Not all clients (i.e. mobile) like text files, and they usually result in a file being downloaded.

Other idea would be to make the part that does the markdown escaping into a helper, have commands that add/edit tags to check the length with respect to that escaped text instead. That won't solve tags that already exceed it, but at least it keeps both in working order?

**Comment by quachtridat** [comment]
> Other idea would be to make the part that does the markdown escaping into a helper, have commands that add/edit tags to check the length with respect to that escaped text instead. That won't solve tags that already exceed it, but at least it keeps both in working order?

I'm OK with that. Going this way, we just don't let users make long ones.
