### ISSUE TITLE
[Birthday] Allow users to set their own birthday. 

### ISSUE THREAD

**Issue by ghost** [SFUAnime/Ren#570]
### What component of Red (cog, command, API) would you like to see improvements on?

birthday

### Describe the enhancement you're suggesting.

On the current state of the cog users are not allowed to submit their own birthday, requiring an Moderator/Admin to do so. A quality of life improvement would be adding a command that lets user submit their own birthday or making the user an optional parameter. 

### Anything else?

On [this repository](https://github.com/Injabie3/lui-cogs-v3) the owner instructed to open issues here instead. I apologize if this is not the correct place.

**Comment by Injabie3** [comment]
The initial intention was to make it only visible for mod/admin to avoid abuse. That being said, we can look at adding a toggle that can expose this command to everyone on a given server, and a server mod/admin can enable it to allow users to set their own birthday.

**Comment by quachtridat** [comment]
@gabuch2 @Injabie3 
We need to be a bit more specific. I believe a normal server member (not with admin/moderator permissions/privileges) should be able to set his/her/their birthday only once if it doesn't exist in the cog's store? Admins and moderators can overwrite and/or delete still.

**Comment by Injabie3** [comment]
That sounds reasonable IMO. A birthday shouldn't change, and if it needs to be removed, then the person should use `[p]forgetme` (or whatever it is, the one built into Red, but in any case we haven't implemented this yet), or ask a moderator to remove.
