### ISSUE TITLE
[CI] Style check fails due to Tox 4 deprecating `whitelist_externals`

### ISSUE THREAD

**Issue by quachtridat** [SFUAnime/Ren#597]
## Summary

Tox 4 deprecates `whitelist_externals` in favor of `allowlist_externals`, making GH Actions run [#68](https://github.com/SFUAnime/Ren/actions/runs/3680525071) (and subsequent runs) fail.

## Details

Due to Tox 4 deprecating configuration option `whitelist_externals` (in favor of `allowlist_externals`), plus existing workflows don't specify a `tox` major version which causes `pip` to select the latest Tox version (v4), the existing allowlist/whitelist in `tox.ini` ceases to take effect and makes GH Actions runs from [#68](https://github.com/SFUAnime/Ren/actions/runs/3680525071) onwards to fail during workflow *Tox - Style* with the following trailing log lines:

```text
style: commands[0]> make stylediff
style: failed with make is not allowed, use allowlist_externals to allow it
.pkg: _exit> python /opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/pyproject_api/_backend.py True setuptools.build_meta
  style: FAIL code 1 (25.52 seconds)
  evaluation failed :( (25.60 seconds)
Error: Process completed with exit code 1.
```

## Suggested solutions

1. Upstream [Cog-Creators/Red-DiscordBot](https://github.com/Cog-Creators/Red-DiscordBot) has a fix by gating `tox` version with selector `<4` to favor Tox 3 over Tox 4: https://github.com/Cog-Creators/Red-DiscordBot/pull/5924. This change modifies GH Actions workflows and dependency resolution logic so care should be taken if we opt for cherry-picking this.

2. Alternatively, we can apply upstream commits during `discord.py` v2 migration. During this process we'll reduce our dependency gap & API differences between our code and upstream code, which will hopefully alleviate headaches when adopting upstream package-level changes.

**Comment by Injabie3** [comment]
We have opted for 2, and I have fixed the outstanding style issues unrelated to this Tox dependency, which has resulted in CI passing. Closing.
