### ISSUE TITLE
[SlashSync] Add cog

### ISSUE THREAD

**Issue by Injabie3** [SFUAnime/Ren#603]
In dpy2, the `hybrid_command` decorator is available, which allows a command to be invoked by the current `[p]command` as well as the newer slash method `/command`. In order for the slash command to be registered with Discord, we need to [`sync`][1] the command tree with Discord to pick up the new commands and send the interaction to the correct handler.

We should create a simple cog that satisfies the following:
- Automatically re-syncs the command tree when the bot starts up **and** is ready (i.e. `await self.bot.wait_until_red_ready()`).
- Has a command (i.e. `sync`) to manually trigger a command tree re-sync.

[1]: https://discordpy.readthedocs.io/en/stable/ext/commands/commands.html#hybrid-commands

**Comment by quachtridat** [comment]
Attaching this here as a syncing FAQ: https://gist.github.com/AbstractUmbra/a9c188797ae194e592efe05fa129c57f/.
This can be obtained via `?tag slash commands` in discord.py Discord server.
