### ISSUE TITLE
[Highlight] Delayed notifications.

### ISSUE THREAD

**Issue by Injabie3** [SFUAnime/Ren#61]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [x] Bug

### Brief description of the problem
Need to investigate the following: highlight notifications show up after a long delay period:

![screenshot](https://cdn.discordapp.com/attachments/223595096661164033/456309682152275979/Capture_2018-06-12-21-10-53.png)

### Expected behavior
Upon highlight word trigger, gather context for 5 seconds, and DM user.

### Actual behavior
Delay of upwards of 4 hours.

### Steps to reproduce

1. ???
2. ???
3. 
4.

**Comment by Injabie3** [comment]
Reopening because of 10 minute delay:
![2018-09-04_21-58-03](https://user-images.githubusercontent.com/6710854/45072026-fdd0d880-b08d-11e8-9582-ede7d19ceb47.jpg)

**Comment by Injabie3** [comment]
~8min delay
![image](https://user-images.githubusercontent.com/6710854/46590525-cc6e7280-ca68-11e8-9ae7-df6324ca8cc6.png)

**Comment by KamiCreed** [comment]
Is there something that delays it in order to gather context **after** the highlighted word? Maybe that is Ok? Or do we want it nearly right away?

**Comment by Injabie3** [comment]
Now that we have the ability to jump, we can probably remove the delay in gathering context, and just show X number of messages before the triggered message.  Now that I think about it, it might also be due to stacked delays across iteration of this for loop, in which case it should be refactored.
