### ISSUE TITLE
Add alternative to twitter video embeds

### ISSUE THREAD

**Issue by xXJadeRabbitXx** [SFUAnime/Ren#644]
### Type of feature request

Cog

### Description of the feature you're suggesting

twittew embeds suck on discowd wight nyow, i-it seems vxtwittew is a bettew awtewnyative

so OwO w-wouwd be nyice if the x3 bot automaticawwy c-can update the x3 winks t-to use vxtwittew instead

**Comment by Injabie3** [comment]
Merged in #645, closing
