### ISSUE TITLE
[LeaderBoard] Text color not consistant

### ISSUE THREAD

**Issue by zach1502** [SFUAnime/Ren#83]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [x] Bug

### Brief description of the problem
Some text isn't the same color as the rest of the text.

### Expected behavior
<img width="665" alt="screen shot 2018-08-28 at 4 44 23 pm" src="https://user-images.githubusercontent.com/22262354/44756988-aa84e600-aae1-11e8-98e9-ba3885e15c99.png">

### Actual behavior
<img width="692" alt="screen shot 2018-08-28 at 4 35 43 pm" src="https://user-images.githubusercontent.com/22262354/44756793-f4b99780-aae0-11e8-8af0-4dedad4712b4.png">

### Steps to reproduce

1.  Go to #bot_spam
2.  Type "renleaderboard"
3.  Press the "enter" key (or return, they both work)
4.  Profit

**Comment by Injabie3** [comment]
Probably can append `text` to the opening \`\`\` to disable syntax highlighting.

**Comment by zach1502** [comment]
<img width="669" alt="screen shot 2018-09-15 at 8 35 38 pm" src="https://user-images.githubusercontent.com/22262354/45592604-faa7d900-b926-11e8-937c-3bd9856c46fb.png">
:thonk:

**Comment by Injabie3** [comment]
> Probably can append `text` to the opening ``` to disable syntax highlighting.

It's probably thinking it's Unicode or something.  Nonetheless, doing the above should get rid of this.
